### ISSUE TITLE
Rails 5 Mongoid support

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines-audit_trail#8]
As-is, I'm going to comment out the `backend/mongoid_spec.rb` on the `rails-5` branch.  I don't use Mongoid so I am unfamiliar with the setup.

I'm sure this will be a quick fix for a Mongoid user.

I'm getting this error:

```
gems/mongoid-6.0.0.beta/lib/mongoid/config.rb:255:in `clients=':  (Mongoid::Errors::NoClientsConfig)
message:
  No clients configuration provided.
summary:
  Mongoid's configuration requires that you provide details about each client that can be connected to, and requires in the clients config at least 1 default client to exist.
resolution:
  Double check your mongoid.yml to make sure that you have a top-level clients key with at least 1 default client configuration for it. You can regenerate a new mongoid.yml for assistance via `rails g mongoid:config`.

 Example:
   development:
     clients:
       default:
         database: mongoid_dev
         hosts:
           - localhost:27017

        from gems/mongoid-6.0.0.beta/lib/mongoid/config.rb:132:in `load_configuration'
        from gems/mongoid-6.0.0.beta/lib/mongoid/config.rb:89:in `load!'
        from gems/mongoid-6.0.0.beta/lib/mongoid.rb:99:in `load!'
        from /Users/kross/projects/state_machines-audit_trail/spec/helpers/mongoid.rb:4:in `<top (required)>'
```

Commit will be linked below.

**Comment by rosskevin** [comment]
Mongo db support is being removed on 2.x, see #10.
